### ISSUE TITLE
Does not work with ecto 2.0, seemingly due to too tight of a version requirement.

### ISSUE THREAD

**Issue by OvermindDL1** [jeffweiss/ecto_ldap#13]
Library needs the ecto version bumped (to something like `~> 1.1 or ~> 2.0 or ~> 2.0.0-rc5` or so), and needs the new behaviour callback added, as well as the integration test should include Ecto's schemas file, not the models file.

**Comment by jeffweiss** [comment]
Closed via #15.
For ecto >= 2, use ecto_ldap >= 0.3
